### ISSUE TITLE
Customizing the mention's rendering and metadata

### ISSUE THREAD

**Issue by andrictham** [sodenn/lexical-beautiful-mentions#101]
First of all, thank you for open sourcing this! This is the most fully-featured open-source mentions implementation I've come across so far. 

Two questions:

1. Is there anyway to get a ref to the mention tags that are created in the editor, or attach an event listener to it, or swap it out for another React component?

2. Is there a way I can add additional metadata to each mention (a unique ID, for instance), and have the editor track it so I can later access it when serializing the editor state? Otherwise, how can I access the state of the mentions tracked by the extension?

I see there's a way to customize the menu and menu items in the suggestions dropdown, but how can I customize the mentions rendered in the editor?

I’m trying to build an editor where users can create "variables" in a similar way to mentions. I need to track (using a unique ID) of each variable so I can save it to the database later. I also want to add additional metadata that users can define (such as a default value for the variable).

**Comment by sodenn** [comment]
Thank you @andrictham!

1. The mentions in the editor are lexical [DecoratorNodes](https://lexical.dev/docs/concepts/nodes#decoratornode). You can receive them by using the `$nodesOfType` helper:
```typescript
function MentionNodesChangePlugin({
  onChange,
}: {
  onChange: (mentions: BeautifulMentionNode[]) => void;
}) {
  const [editor] = useLexicalComposerContext();
  useEffect(() => {
    const unregister = editor.registerUpdateListener(() => {
      editor.getEditorState().read(() => {
        const mentions = $nodesOfType(BeautifulMentionNode);
        onChange(mentions);
      });
    });
    return () => {
      unregister();
    };
  }, [editor, onChange]);
}
```
But I'm not sure if it's possible to get the DOM representations of these nodes, if that's what you meant by "ref". Ideally there would be a `mentionComponent` prop, similar to the `menuComponent` and `menuItemComponent` prop. Then, the users of this plugin could use their own React component. But this is not possible, because the editor state is built with the registered nodes and not the plugins ☹️. But you can use the editor theme to make visual adjustments if that helps.

2. Currently not. How should this additional metadata then get into the plugin, via the `items` prop? This seems to be related to #44

**Comment by andrictham** [comment]
> I'm not sure if it's possible to get the DOM representations of these nodes, if that's what you meant by "ref"

What I’m trying to achieve is to add event handlers so that I can add tooltips on hover or a popover on click.

If I can pass in a React component for `mentionComponent` as you suggested, where the mention’s label is available as a prop, then I can control rendering and also enrich the mention with external state (e.g., from the database), even if the editor doesn’t keep track of that state.

**Comment by sodenn** [comment]
@andrictham In the future, there will be an option to add additional metadata to mentions. Maybe this will be useful for your use case. E.g.:
```
'@': [
  { name: 'Anton', id: '...' },
  { name: 'Boris', email: '...' },
],
```

> 2. Control rendering of the mention, beyond just styles. I want to add event handlers, so that I can display a tooltip on hover or a popover on click.

There is an option to override the behavior of Lexical Nodes. So you can override the default `BeautifulMentionNode` class and create your own `BeautifulMentionNodeWithTooltip` call. See https://lexical.dev/docs/concepts/node-replacement

**Comment by andrictham** [comment]
@sodenn Great! Is this a change you’re likely to make soon?
