### ISSUE TITLE
Mention with initial Text for Edit Text Cases

### ISSUE THREAD

**Issue by sangpenciptajs** [sodenn/lexical-beautiful-mentions#267]
Is there a way to apply mention from a text that returned from the editor?
I try to implement mention on a dialog, when dialog is closed, the text is passed to other component. 
I have edit button and when I click it, I pass it back to editor and set using editorConfig initText.

```ts
const editorConfig = {
 namespace: "name",
 onError(error: any) {
  throw error;
 },
  nodes: [BeautifulMentionNode],
  editorState: () => {
      const root = $getRoot();
      root.clear();
      const p = $createParagraphNode();
      p.append($createTextNode(initText));
      root.append(p);
    }
  };
```

How can I apply it? because its just a plain text in editor. thanks

**Comment by sodenn** [comment]
Hi @sangpenciptajs. You can use `$convertToMentionNodes` helper function for this purpose.

**Comment by sangpenciptajs** [comment]
@sodenn do you have specific implementation of it?

**Comment by sodenn** [comment]
Does the `$convertToMentionNodes` function work for you? You can find an example of its usage in the [Demo App](https://github.com/sodenn/lexical-beautiful-mentions/blob/main/www/lib/editor-config.ts).

**Comment by sangpenciptajs** [comment]
@sodenn I found that convertToMentionNodes only works for mention that have no space and I think only string, even I add allowSpace. 

@hello world @hello world :x: doesnt work
@{hello} @{world} :x: doesnt work
@hello @world :heavy_check_mark: work

**Comment by sodenn** [comment]
Hi @sangpenciptajs, you can adjust the regex that looks for mentions. Use the last parameter of the `$convertToMentionNodes` function to pass a string with the punctuation you want to allow. In your case, you can use the following:

```diff
- \\.,\\*\\?\\$\\|#{}\\(\\)\\^\\[\\]\\\\/!%'\"~=<>_:; // this is the default
+ \\.,\\*\\?\\$\\|#\\(\\)\\^\\[\\]\\\\/!%'\"~=<>_:;   // without the {}
```

You also need to tell the plugin about the new set of punctuation characters. Add the punctuation prop to the mention plugin:

```tsx
<BeautifulMentionsPlugin
  ...
  punctuation={`\\.,\\*\\?\\$\\|#\\(\\)\\^\\[\\]\\\\/!%'"~=<>_:;`}
/>
```

But the `$convertToMentionNodes` helper function only works for mentions that have no space. The helper function does not know where the mention starts and ends. You need to connect the words that make up the mention with a dash or underscore for example. If you don't want to use a dash or underscore, it might be better to store the editor state as JSON or HTML instead of plain text: https://lexical.dev/docs/concepts/serialization
