### ISSUE TITLE
Intermittent Incorrect Positioning of Mention Menu in Multi-line Textarea

### ISSUE THREAD

**Issue by vekaev** [sodenn/lexical-beautiful-mentions#304]
**Describe the bug**
In the `lexical-beautiful-mentions` plugin, the menu list sometimes appears in the wrong position when used in a multi-line textarea.

**Expected behavior**
The menu list should consistently appear right below the line where the mention is being typed, regardless of whether the textarea is single-line or multi-line.

**Screenshots**
Wrong:
<img width="471" alt="image" src="https://github.com/sodenn/lexical-beautiful-mentions/assets/54939386/871d1412-d7db-4e04-a8a0-f58a1693a7ba">
Correct:
<img width="402" alt="image" src="https://github.com/sodenn/lexical-beautiful-mentions/assets/54939386/a568fd4c-0dee-405d-8826-61a6de7896ef">

**Comment by sodenn** [comment]
Hi @vekaev. I suggest to use absolute positioning for your menu component. This allows you to place the menu exactly where you want it. Take a look at the menu component in the [example](https://github.com/sodenn/lexical-beautiful-mentions/blob/main/www/components/Menu.tsx). I moved the menu a bit down so that it is not directly below the text.
