### ISSUE TITLE
Copy paste mentions fails with PlainTextPlugin

### ISSUE THREAD

**Issue by WesleyKapow** [sodenn/lexical-beautiful-mentions#375]
**Describe the bug**
Copy paste of mentions does not work with `PlainTextPlugin`

**To Reproduce**
1. Use `PlainTextPlugin`
2. Copy and paste text which includes a mention.
3. Notice it pastes as plain and not with the mention.

**Expected behavior**
Expect pasting to include the mention decoration.

**Comment by sodenn** [comment]
Hi @WesleyKapow. Until v0.1.25, the plugin had a build-in copy & past functionality. But it did not work well (https://github.com/sodenn/lexical-beautiful-mentions/pull/291). The mentions metadata was lost when copying. Since lexical already has a well working build-in copy & paste functionality, the recommendation is to switch from `PlainTextPlugin` to `RichTextPlugin`.

**Comment by WesleyKapow** [comment]
Got it. Was hoping to avoid RichTextPlugin as I don't want any styles but I was able to use CSS to just hide bold/italic styling if the user did happen to do cmd+b or cmd+i.

May want to update the README examples if this plugin is intended to only work with RichTextPlugin. Could even mention PlainTextPlugin comes with this one bug.
