### ISSUE TITLE
Menu disappears when moving the cursor during active search (within the search string)

### ISSUE THREAD

**Issue by vs-amzn** [sodenn/lexical-beautiful-mentions#462]
**Describe the bug**

When starting a search for a mention, when you move the cursor back (while the search is still active), the menu disappears.

**To Reproduce**
1. Go to demo site
2. Type in "@Gi"
3. Use arrow key and move cursor from end of "@Gi" to between "G" and "i" in "@Gi"
4. See the menu go away

**Expected behavior**
The menu should still be there.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sodenn** [comment]
Hi @vs-amzn. This is the expected behavior. The mention menu is designed to disappear when the cursor is moved away from the end of the mention. What is the use case for keeping the menu open?

**Comment by vs-amzn** [comment]
Gotcha, thanks.

The use case is that lets say there's a typo when searching and you want to go back and change the beginning of the search string, it would be nice to see the menu still open as I do that.

Would it be possible to support this?

**Comment by sodenn** [comment]
I think it would be challenging to support this because the beautiful-mentions plugin uses the `LexicalTypeaheadMenuPlugin` and its trigger function. The trigger function is called with the text before the cursor. So, when the cursor is moved back, the text from the trigger function contains less information than before. This leads to different search results whenever the cursor is moved. I think this could be confusing for the user.

**Example**
Given the following menu items:
- `@Alice`
- `@Andrew`
- `@Andy`
- `@Alex`

When the user types `@Andy`, the menu only shows `Andy`. If the user moves the cursor one character back, the menu suddenly shows `Andrew` and `Andy` (because the trigger function is called with `@And`). And if the user moves the cursor back to `@A` all menu items are shown.

**Comment by vs-amzn** [comment]
Ahh I see -- thank you for clarifying that. Appreciate it. 

This behavior is also reproducible in the lexical playground through the menus generated by `:` and `/`.
