### ISSUE TITLE
Question: Possible to create new mentions when using customMenu?

### ISSUE THREAD

**Issue by fakob** [sodenn/lexical-beautiful-mentions#474]
Hi,
thanks for the work on this great plugin. It does enhance lexical in a very important way. At least to me :-)
Now I was wondering if there is a way to allow creating new mentions when using a customMenu? I might have overlooked it, but using `creatable` seems to only apply to default menus?

**Comment by sodenn** [comment]
Hi @fakob. You can also create new mentions with custom menus. Take a look at the example app: https://github.com/sodenn/lexical-beautiful-mentions/blob/37e1729e923429906bb607300a81974ea1045c7b/www/components/Menu.tsx#L34-L47

In the above code, the `li` element receives the `children` prop that contains the text of the mention. In case of a new mention, the text is _Add "newmention"_. You can change this text by passing a string to the `creatable` prop. For example:
```
creatable={`Add user "{{name}}"`} // {{name}} will be replaced by the text of the new mention
```

If you need more control of what is displayed in the menu item, you can use the data from the `item` prop instead of passing the `children` prop to the `li` element. For example:
```
<li ref={ref} ...>
  <bold>{item.trigger}</bold><span>{item.value}</span>
</li>
```

**Comment by fakob** [comment]
Thanks @sodenn for the fast reply. 
I didn't have much time now to try this out, but at first test, I did not get the `Add user` entry to show up. Could it be because I have additional metadata? My item structure looks like this:
```
 item: {
   data: { id, displayvalue, realvalue, trigger, value },
 },
```

**Comment by sodenn** [comment]
Adding new mentions also works if existing mentions have additional metadata. You can see this in the [example app](https://lexical-beautiful-mentions-docs.vercel.app/?new=true) by activate the **creatable** checkbox. Can you provide a [codesandbox](https://codesandbox.io/) with your code, so I can take a look at it?

**Comment by fakob** [comment]
Hi @sodenn

Due to my special setup I had completely ignored `value` and only used metadata in `data`. This seems to have been the issue that it had not worked for me initially. 
In addition I noticed that for my use case I would rather need a general "Create new entry" item in the dropdown, independent of if the user types something or not. But I guess this is something I should just be able to attach to my list.

Sorry for all the fuzz. This was clearly a user error :-)
